#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 04-11-11 05:23 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.8.0.0
#endregion


using System;
using System.Web;
using System.Configuration;


public class AsmxHelpModule : System.Web.IHttpModule
{
    
    private AsmxHelpModule()
    {
    }
    
    private void Application_BeginRequest(object sender, System.EventArgs e)
    {
        string requestPath = HttpContext.Current.Request.RawUrl;
        requestPath = requestPath.Trim();
        requestPath = requestPath.ToLower();
        string setting = ConfigurationManager.AppSettings["disableWsdl"];
        if (((setting != null) 
                    && (setting != "")))
        {
            setting = setting.ToLower();
            string[] asmxFileNames = setting.Split(new char[] {
                        ';'});
            for (int i = 0; (i < asmxFileNames.Length); i = (i + 1))
            {
                string fn = asmxFileNames[i];
                if (((requestPath.IndexOf((fn + "?wsdl")) > 0) 
                            || (requestPath.IndexOf((fn + "?disco")) > 0)))
                {
                    throw new HttpException(404, "");
                }
            }
        }
    }
    
    public virtual void Init(HttpApplication app)
    {
        app.BeginRequest += new System.EventHandler(this.Application_BeginRequest);
    }
    
    public virtual void Dispose()
    {
    }
}
