
package net.sertifi.apps.services;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GatewaySoap", targetNamespace = "http://apps.sertifi.net/services/")
@XmlSeeAlso({
    https.apps_sertifi_net.services.linkparameter.ObjectFactory.class,
    net.sertifi.apps.services.ObjectFactory.class,
    net.sertifi.apps.services.linkparameter.ObjectFactory.class
})
public interface GatewaySoap {


    /**
     * 
     * @param pstrField1
     * @param pstrField2
     * @param pstrField3
     * @param pstrField4
     * @param pstrSecondSigners
     * @param pstrPassword
     * @param pstrSignType
     * @param pstrSigners
     * @param pstrEmailMessage
     * @param pstrSenderEmail
     * @param pstrAPICode
     * @param pstrCCs
     * @param pstrFileName
     * @param pstrSenderName
     * @param pstrCosign
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateSignatureRequest", action = "http://apps.sertifi.net/services/CreateSignatureRequest")
    @WebResult(name = "CreateSignatureRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "CreateSignatureRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreateSignatureRequest")
    @ResponseWrapper(localName = "CreateSignatureRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreateSignatureRequestResponse")
    public String createSignatureRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_SenderEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSenderEmail,
        @WebParam(name = "pstr_SenderName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSenderName,
        @WebParam(name = "pstr_FileName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileName,
        @WebParam(name = "pstr_Signers", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSigners,
        @WebParam(name = "pstr_SecondSigners", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSecondSigners,
        @WebParam(name = "pstr_CCs", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCCs,
        @WebParam(name = "pstr_Cosign", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCosign,
        @WebParam(name = "pstr_SignType", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignType,
        @WebParam(name = "pstr_Password", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrPassword,
        @WebParam(name = "pstr_Field1", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrField1,
        @WebParam(name = "pstr_Field2", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrField2,
        @WebParam(name = "pstr_Field3", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrField3,
        @WebParam(name = "pstr_Field4", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrField4,
        @WebParam(name = "pstr_EmailMessage", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmailMessage);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrAPICode
     * @param pstrXml
     * @param pbytFile
     * @param pstrFileName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddDocumentToRequest", action = "http://apps.sertifi.net/services/AddDocumentToRequest")
    @WebResult(name = "AddDocumentToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddDocumentToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddDocumentToRequest")
    @ResponseWrapper(localName = "AddDocumentToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddDocumentToRequestResponse")
    public String addDocumentToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pbyt_File", targetNamespace = "http://apps.sertifi.net/services/")
        byte[] pbytFile,
        @WebParam(name = "pstr_FileName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileName,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "pstr_Xml", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrXml);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrPdfID
     * @param pstrAPICode
     * @param pstrXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddPrepopulatedPdfToRequest", action = "http://apps.sertifi.net/services/AddPrepopulatedPdfToRequest")
    @WebResult(name = "AddPrepopulatedPdfToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddPrepopulatedPdfToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddPrepopulatedPdfToRequest")
    @ResponseWrapper(localName = "AddPrepopulatedPdfToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddPrepopulatedPdfToRequestResponse")
    public String addPrepopulatedPdfToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_PdfID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrPdfID,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "pstr_Xml", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrXml);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param permissions
     * @param pstrAPICode
     * @param returnId
     * @param pstrLibraryId
     * @param customMetadataXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddReferenceDocumentFromLibrary", action = "http://apps.sertifi.net/services/AddReferenceDocumentFromLibrary")
    @WebResult(name = "AddReferenceDocumentFromLibraryResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddReferenceDocumentFromLibrary", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddReferenceDocumentFromLibrary")
    @ResponseWrapper(localName = "AddReferenceDocumentFromLibraryResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddReferenceDocumentFromLibraryResponse")
    public String addReferenceDocumentFromLibrary(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_LibraryId", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrLibraryId,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "returnId", targetNamespace = "http://apps.sertifi.net/services/")
        boolean returnId,
        @WebParam(name = "permissions", targetNamespace = "http://apps.sertifi.net/services/")
        ArrayOfReferenceDocumentPermission permissions,
        @WebParam(name = "customMetadataXML", targetNamespace = "http://apps.sertifi.net/services/")
        String customMetadataXML);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param permissions
     * @param pstrAPICode
     * @param returnId
     * @param customMetadataXML
     * @param pbytFile
     * @param pstrFileName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddReferenceDocumentToRequest", action = "http://apps.sertifi.net/services/AddReferenceDocumentToRequest")
    @WebResult(name = "AddReferenceDocumentToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddReferenceDocumentToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddReferenceDocumentToRequest")
    @ResponseWrapper(localName = "AddReferenceDocumentToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddReferenceDocumentToRequestResponse")
    public String addReferenceDocumentToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pbyt_File", targetNamespace = "http://apps.sertifi.net/services/")
        byte[] pbytFile,
        @WebParam(name = "pstr_FileName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileName,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "returnId", targetNamespace = "http://apps.sertifi.net/services/")
        boolean returnId,
        @WebParam(name = "permissions", targetNamespace = "http://apps.sertifi.net/services/")
        ArrayOfReferenceDocumentPermission permissions,
        @WebParam(name = "customMetadataXML", targetNamespace = "http://apps.sertifi.net/services/")
        String customMetadataXML);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrAPICode
     * @param pbytFile
     * @param pstrFileName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddInstructionalDocumentToRequest", action = "http://apps.sertifi.net/services/AddInstructionalDocumentToRequest")
    @WebResult(name = "AddInstructionalDocumentToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddInstructionalDocumentToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddInstructionalDocumentToRequest")
    @ResponseWrapper(localName = "AddInstructionalDocumentToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddInstructionalDocumentToRequestResponse")
    public String addInstructionalDocumentToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pbyt_File", targetNamespace = "http://apps.sertifi.net/services/")
        byte[] pbytFile,
        @WebParam(name = "pstr_FileName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileName,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle);

    /**
     * 
     * @param sequence
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddSignerToRequest", action = "http://apps.sertifi.net/services/AddSignerToRequest")
    @WebResult(name = "AddSignerToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddSignerToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSignerToRequest")
    @ResponseWrapper(localName = "AddSignerToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSignerToRequestResponse")
    public String addSignerToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail,
        @WebParam(name = "sequence", targetNamespace = "http://apps.sertifi.net/services/")
        Integer sequence);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddSecondSignerToRequest", action = "http://apps.sertifi.net/services/AddSecondSignerToRequest")
    @WebResult(name = "AddSecondSignerToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddSecondSignerToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSecondSignerToRequest")
    @ResponseWrapper(localName = "AddSecondSignerToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSecondSignerToRequestResponse")
    public String addSecondSignerToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddCCToRequest", action = "http://apps.sertifi.net/services/AddCCToRequest")
    @WebResult(name = "AddCCToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddCCToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddCCToRequest")
    @ResponseWrapper(localName = "AddCCToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddCCToRequestResponse")
    public String addCCToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmailMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InviteSigners", action = "http://apps.sertifi.net/services/InviteSigners")
    @WebResult(name = "InviteSignersResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "InviteSigners", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSigners")
    @ResponseWrapper(localName = "InviteSignersResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSignersResponse")
    public String inviteSigners(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_EmailMessage", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmailMessage);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetDocumentSummary", action = "http://apps.sertifi.net/services/GetDocumentSummary")
    @WebResult(name = "GetDocumentSummaryResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetDocumentSummary", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentSummary")
    @ResponseWrapper(localName = "GetDocumentSummaryResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentSummaryResponse")
    public byte[] getDocumentSummary(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmailMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InviteSignersWithAttachment", action = "http://apps.sertifi.net/services/InviteSignersWithAttachment")
    @WebResult(name = "InviteSignersWithAttachmentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "InviteSignersWithAttachment", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSignersWithAttachment")
    @ResponseWrapper(localName = "InviteSignersWithAttachmentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSignersWithAttachmentResponse")
    public String inviteSignersWithAttachment(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_EmailMessage", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmailMessage);

    /**
     * 
     * @param pstrFileID
     * @param pstrSigner
     * @param pstrAPICode
     * @param pstrEmailMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InviteSigner", action = "http://apps.sertifi.net/services/InviteSigner")
    @WebResult(name = "InviteSignerResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "InviteSigner", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSigner")
    @ResponseWrapper(localName = "InviteSignerResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.InviteSignerResponse")
    public String inviteSigner(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_EmailMessage", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmailMessage,
        @WebParam(name = "pstr_Signer", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSigner);

    /**
     * 
     * @param pstrEndDate
     * @param pstrAPICode
     * @param pstrStartDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFilesStatus", action = "http://apps.sertifi.net/services/GetFilesStatus")
    @WebResult(name = "GetFilesStatusResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetFilesStatus", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFilesStatus")
    @ResponseWrapper(localName = "GetFilesStatusResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFilesStatusResponse")
    public String getFilesStatus(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_StartDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrStartDate,
        @WebParam(name = "pstr_EndDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEndDate);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMinimalFileStatus", action = "http://apps.sertifi.net/services/GetMinimalFileStatus")
    @WebResult(name = "GetMinimalFileStatusResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetMinimalFileStatus", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetMinimalFileStatus")
    @ResponseWrapper(localName = "GetMinimalFileStatusResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetMinimalFileStatusResponse")
    public String getMinimalFileStatus(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrFileID
     * @param includeDocumentDatabaseXML
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFileStatus", action = "http://apps.sertifi.net/services/GetFileStatus")
    @WebResult(name = "GetFileStatusResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetFileStatus", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFileStatus")
    @ResponseWrapper(localName = "GetFileStatusResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFileStatusResponse")
    public String getFileStatus(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "includeDocumentDatabaseXML", targetNamespace = "http://apps.sertifi.net/services/")
        boolean includeDocumentDatabaseXML);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFileSigners", action = "http://apps.sertifi.net/services/GetFileSigners")
    @WebResult(name = "GetFileSignersResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetFileSigners", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFileSigners")
    @ResponseWrapper(localName = "GetFileSignersResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetFileSignersResponse")
    public String getFileSigners(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrEndDate
     * @param pstrStatus
     * @param pstrAPICode
     * @param pstrStartDate
     * @param pstrSigners
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDocumentsStatus", action = "http://apps.sertifi.net/services/GetDocumentsStatus")
    @WebResult(name = "GetDocumentsStatusResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetDocumentsStatus", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentsStatus")
    @ResponseWrapper(localName = "GetDocumentsStatusResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentsStatusResponse")
    public String getDocumentsStatus(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_StartDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrStartDate,
        @WebParam(name = "pstr_EndDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEndDate,
        @WebParam(name = "pstr_Status", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrStatus,
        @WebParam(name = "pstr_Signers", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSigners);

    /**
     * 
     * @param pstrAPICode
     * @param pstrEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserInfo", action = "http://apps.sertifi.net/services/GetUserInfo")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetUserInfoResponse")
    public String getUserInfo(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveSignatureRequest", action = "http://apps.sertifi.net/services/RemoveSignatureRequest")
    @WebResult(name = "RemoveSignatureRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemoveSignatureRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveSignatureRequest")
    @ResponseWrapper(localName = "RemoveSignatureRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveSignatureRequestResponse")
    public String removeSignatureRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveDocument", action = "http://apps.sertifi.net/services/RemoveDocument")
    @WebResult(name = "RemoveDocumentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemoveDocument", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveDocument")
    @ResponseWrapper(localName = "RemoveDocumentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveDocumentResponse")
    public String removeDocument(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveReferenceDocument", action = "http://apps.sertifi.net/services/RemoveReferenceDocument")
    @WebResult(name = "RemoveReferenceDocumentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemoveReferenceDocument", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveReferenceDocument")
    @ResponseWrapper(localName = "RemoveReferenceDocumentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveReferenceDocumentResponse")
    public String removeReferenceDocument(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pintSequence
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrEmail
     * @param pstrSignerType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveUser", action = "http://apps.sertifi.net/services/RemoveUser")
    @WebResult(name = "RemoveUserResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemoveUser", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveUser")
    @ResponseWrapper(localName = "RemoveUserResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveUserResponse")
    public String removeUser(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail,
        @WebParam(name = "pstr_SignerType", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerType,
        @WebParam(name = "pint_Sequence", targetNamespace = "http://apps.sertifi.net/services/")
        int pintSequence);

    /**
     * 
     * @param pshrSequence
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrNewEmail
     * @param pstrOriginalEmail
     * @param pstrSignerType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EditUser", action = "http://apps.sertifi.net/services/EditUser")
    @WebResult(name = "EditUserResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "EditUser", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.EditUser")
    @ResponseWrapper(localName = "EditUserResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.EditUserResponse")
    public String editUser(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_OriginalEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrOriginalEmail,
        @WebParam(name = "pstr_NewEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrNewEmail,
        @WebParam(name = "pstr_SignerType", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerType,
        @WebParam(name = "pshr_Sequence", targetNamespace = "http://apps.sertifi.net/services/")
        short pshrSequence);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrNewEmail
     * @param pstrOriginalEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeSignerEmail", action = "http://apps.sertifi.net/services/ChangeSignerEmail")
    @WebResult(name = "ChangeSignerEmailResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "ChangeSignerEmail", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ChangeSignerEmail")
    @ResponseWrapper(localName = "ChangeSignerEmailResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ChangeSignerEmailResponse")
    public String changeSignerEmail(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_OriginalEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrOriginalEmail,
        @WebParam(name = "pstr_NewEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrNewEmail);

    /**
     * 
     * @param pstrFileID
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSigningLink", action = "http://apps.sertifi.net/services/GetSigningLink")
    @WebResult(name = "GetSigningLinkResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetSigningLink", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetSigningLink")
    @ResponseWrapper(localName = "GetSigningLinkResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetSigningLinkResponse")
    public String getSigningLink(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSignedDocumentEmail", action = "http://apps.sertifi.net/services/SendSignedDocumentEmail")
    @WebResult(name = "SendSignedDocumentEmailResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "SendSignedDocumentEmail", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SendSignedDocumentEmail")
    @ResponseWrapper(localName = "SendSignedDocumentEmailResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SendSignedDocumentEmailResponse")
    public String sendSignedDocumentEmail(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "DownloadSignedDocument", action = "http://apps.sertifi.net/services/DownloadSignedDocument")
    @WebResult(name = "DownloadSignedDocumentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "DownloadSignedDocument", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.DownloadSignedDocument")
    @ResponseWrapper(localName = "DownloadSignedDocumentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.DownloadSignedDocumentResponse")
    public byte[] downloadSignedDocument(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "DownloadFileContents", action = "http://apps.sertifi.net/services/DownloadFileContents")
    @WebResult(name = "DownloadFileContentsResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "DownloadFileContents", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.DownloadFileContents")
    @ResponseWrapper(localName = "DownloadFileContentsResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.DownloadFileContentsResponse")
    public byte[] downloadFileContents(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMaintenanceLink", action = "http://apps.sertifi.net/services/GetMaintenanceLink")
    @WebResult(name = "GetMaintenanceLinkResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetMaintenanceLink", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetMaintenanceLink")
    @ResponseWrapper(localName = "GetMaintenanceLinkResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetMaintenanceLinkResponse")
    public String getMaintenanceLink(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDocumentHash", action = "http://apps.sertifi.net/services/GetDocumentHash")
    @WebResult(name = "GetDocumentHashResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetDocumentHash", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentHash")
    @ResponseWrapper(localName = "GetDocumentHashResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetDocumentHashResponse")
    public String getDocumentHash(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID);

    /**
     * 
     * @param pstrNameSigned
     * @param pstrFileID
     * @param pstrAPICode
     * @param pstrCustomField2
     * @param pstrEmail
     * @param pstrCustomField3
     * @param pstrCustomField1
     * @param pstrDocumentID
     * @param pstrCustomField4
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ApplySignature", action = "http://apps.sertifi.net/services/ApplySignature")
    @WebResult(name = "ApplySignatureResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "ApplySignature", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ApplySignature")
    @ResponseWrapper(localName = "ApplySignatureResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ApplySignatureResponse")
    public String applySignature(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID,
        @WebParam(name = "pstr_NameSigned", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrNameSigned,
        @WebParam(name = "pstr_Email", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEmail,
        @WebParam(name = "pstr_CustomField1", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCustomField1,
        @WebParam(name = "pstr_CustomField2", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCustomField2,
        @WebParam(name = "pstr_CustomField3", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCustomField3,
        @WebParam(name = "pstr_CustomField4", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCustomField4);

    /**
     * 
     * @param pstrEndDate
     * @param pstrAPICode
     * @param pstrStartDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStatusOnChangedFiles", action = "http://apps.sertifi.net/services/GetStatusOnChangedFiles")
    @WebResult(name = "GetStatusOnChangedFilesResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetStatusOnChangedFiles", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetStatusOnChangedFiles")
    @ResponseWrapper(localName = "GetStatusOnChangedFilesResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetStatusOnChangedFilesResponse")
    public String getStatusOnChangedFiles(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_StartDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrStartDate,
        @WebParam(name = "pstr_EndDate", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrEndDate);

    /**
     * 
     * @param pintPage
     * @param pintWidth
     * @param pintHeight
     * @param pstrFileID
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @param pstrCaption
     * @param pintLeft
     * @param pintTop
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddSigningLocation", action = "http://apps.sertifi.net/services/AddSigningLocation")
    @WebResult(name = "AddSigningLocationResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddSigningLocation", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSigningLocation")
    @ResponseWrapper(localName = "AddSigningLocationResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddSigningLocationResponse")
    public String addSigningLocation(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID,
        @WebParam(name = "pint_Page", targetNamespace = "http://apps.sertifi.net/services/")
        int pintPage,
        @WebParam(name = "pint_Top", targetNamespace = "http://apps.sertifi.net/services/")
        int pintTop,
        @WebParam(name = "pint_Left", targetNamespace = "http://apps.sertifi.net/services/")
        int pintLeft,
        @WebParam(name = "pint_Height", targetNamespace = "http://apps.sertifi.net/services/")
        int pintHeight,
        @WebParam(name = "pint_Width", targetNamespace = "http://apps.sertifi.net/services/")
        int pintWidth,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail,
        @WebParam(name = "pstr_Caption", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCaption);

    /**
     * 
     * @param pintPage
     * @param pintWidth
     * @param sequence
     * @param pintHeight
     * @param pintFieldType
     * @param pstrFileID
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @param pstrCaption
     * @param pintLeft
     * @param pintTop
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddLocation", action = "http://apps.sertifi.net/services/AddLocation")
    @WebResult(name = "AddLocationResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddLocation", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddLocation")
    @ResponseWrapper(localName = "AddLocationResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddLocationResponse")
    public String addLocation(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID,
        @WebParam(name = "pint_Page", targetNamespace = "http://apps.sertifi.net/services/")
        int pintPage,
        @WebParam(name = "pint_Top", targetNamespace = "http://apps.sertifi.net/services/")
        int pintTop,
        @WebParam(name = "pint_Left", targetNamespace = "http://apps.sertifi.net/services/")
        int pintLeft,
        @WebParam(name = "pint_Height", targetNamespace = "http://apps.sertifi.net/services/")
        int pintHeight,
        @WebParam(name = "pint_Width", targetNamespace = "http://apps.sertifi.net/services/")
        int pintWidth,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail,
        @WebParam(name = "pstr_Caption", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrCaption,
        @WebParam(name = "pint_FieldType", targetNamespace = "http://apps.sertifi.net/services/")
        int pintFieldType,
        @WebParam(name = "sequence", targetNamespace = "http://apps.sertifi.net/services/")
        Integer sequence);

    /**
     * 
     * @param pintPage
     * @param pstrFileID
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @param pintLeft
     * @param pintTop
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetSigningBoxLocation", action = "http://apps.sertifi.net/services/SetSigningBoxLocation")
    @WebResult(name = "SetSigningBoxLocationResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "SetSigningBoxLocation", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetSigningBoxLocation")
    @ResponseWrapper(localName = "SetSigningBoxLocationResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetSigningBoxLocationResponse")
    public String setSigningBoxLocation(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID,
        @WebParam(name = "pint_Page", targetNamespace = "http://apps.sertifi.net/services/")
        int pintPage,
        @WebParam(name = "pint_Top", targetNamespace = "http://apps.sertifi.net/services/")
        int pintTop,
        @WebParam(name = "pint_Left", targetNamespace = "http://apps.sertifi.net/services/")
        int pintLeft,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail);

    /**
     * 
     * @param pstrTemplateID
     * @param pstrFileID
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @param pstrDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ApplyTemplate", action = "http://apps.sertifi.net/services/ApplyTemplate")
    @WebResult(name = "ApplyTemplateResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "ApplyTemplate", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ApplyTemplate")
    @ResponseWrapper(localName = "ApplyTemplateResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.ApplyTemplateResponse")
    public String applyTemplate(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrDocumentID,
        @WebParam(name = "pstr_TemplateID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTemplateID,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail);

    /**
     * 
     * @param pstrPassword
     * @param lstrRoomID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "VerifyFolderPassword", action = "http://apps.sertifi.net/services/VerifyFolderPassword")
    @WebResult(name = "VerifyFolderPasswordResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "VerifyFolderPassword", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.VerifyFolderPassword")
    @ResponseWrapper(localName = "VerifyFolderPasswordResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.VerifyFolderPasswordResponse")
    public boolean verifyFolderPassword(
        @WebParam(name = "lstr_RoomID", targetNamespace = "http://apps.sertifi.net/services/")
        String lstrRoomID,
        @WebParam(name = "pstr_Password", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrPassword);

    /**
     * 
     * @param pFileID
     * @param pRedirectUrl
     * @param pAPICode
     * @param redirectActions
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetRedirectURL", action = "http://apps.sertifi.net/services/SetRedirectURL")
    @WebResult(name = "SetRedirectURLResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "SetRedirectURL", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetRedirectURL")
    @ResponseWrapper(localName = "SetRedirectURLResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetRedirectURLResponse")
    public String setRedirectURL(
        @WebParam(name = "p_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pAPICode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "p_redirectUrl", targetNamespace = "http://apps.sertifi.net/services/")
        String pRedirectUrl,
        @WebParam(name = "redirectActions", targetNamespace = "http://apps.sertifi.net/services/")
        ArrayOfRedirectOnAction redirectActions);

    /**
     * 
     * @param pApiCode
     * @param parameters
     * @return
     *     returns net.sertifi.apps.services.ArrayOfFileQueryResult
     */
    @WebMethod(operationName = "FileQuery", action = "http://apps.sertifi.net/services/FileQuery")
    @WebResult(name = "FileQueryResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "FileQuery", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.FileQuery")
    @ResponseWrapper(localName = "FileQueryResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.FileQueryResponse")
    public ArrayOfFileQueryResult fileQuery(
        @WebParam(name = "p_ApiCode", targetNamespace = "http://apps.sertifi.net/services/")
        String pApiCode,
        @WebParam(name = "parameters", targetNamespace = "http://apps.sertifi.net/services/")
        ArrayOfSearchParameter parameters);

    /**
     * 
     * @param pFileID
     * @param pApiCode
     * @param pXMLContent
     * @param pDocumentID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetDocumentParameters", action = "http://apps.sertifi.net/services/SetDocumentParameters")
    @WebResult(name = "SetDocumentParametersResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "SetDocumentParameters", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetDocumentParameters")
    @ResponseWrapper(localName = "SetDocumentParametersResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetDocumentParametersResponse")
    public String setDocumentParameters(
        @WebParam(name = "p_ApiCode", targetNamespace = "http://apps.sertifi.net/services/")
        String pApiCode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "p_DocumentID", targetNamespace = "http://apps.sertifi.net/services/")
        String pDocumentID,
        @WebParam(name = "p_XMLContent", targetNamespace = "http://apps.sertifi.net/services/")
        String pXMLContent);

    /**
     * 
     * @param pFileID
     * @param pCustomMetadataXML
     * @param pApiCode
     * @param pXMLContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetSignatureRequestParameters", action = "http://apps.sertifi.net/services/SetSignatureRequestParameters")
    @WebResult(name = "SetSignatureRequestParametersResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "SetSignatureRequestParameters", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetSignatureRequestParameters")
    @ResponseWrapper(localName = "SetSignatureRequestParametersResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.SetSignatureRequestParametersResponse")
    public String setSignatureRequestParameters(
        @WebParam(name = "p_ApiCode", targetNamespace = "http://apps.sertifi.net/services/")
        String pApiCode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "p_XMLContent", targetNamespace = "http://apps.sertifi.net/services/")
        String pXMLContent,
        @WebParam(name = "p_CustomMetadataXML", targetNamespace = "http://apps.sertifi.net/services/")
        String pCustomMetadataXML);

    /**
     * 
     * @param pAPICode
     * @param parameters
     * @return
     *     returns net.sertifi.apps.services.ArrayOfUrlQueryResult
     */
    @WebMethod(operationName = "GetLink", action = "http://apps.sertifi.net/services/GetLink")
    @WebResult(name = "GetLinkResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetLink", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetLink")
    @ResponseWrapper(localName = "GetLinkResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetLinkResponse")
    public ArrayOfUrlQueryResult getLink(
        @WebParam(name = "p_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pAPICode,
        @WebParam(name = "parameters", targetNamespace = "http://apps.sertifi.net/services/")
        ArrayOfLinkParameter parameters);

    /**
     * 
     * @param pFileID
     * @param recurrence
     * @param amount
     * @param pAPICode
     * @param description
     * @param datePaymentDue
     * @param operation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePayment", action = "http://apps.sertifi.net/services/CreatePayment")
    @WebResult(name = "CreatePaymentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "CreatePayment", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreatePayment")
    @ResponseWrapper(localName = "CreatePaymentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreatePaymentResponse")
    public String createPayment(
        @WebParam(name = "p_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pAPICode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "amount", targetNamespace = "http://apps.sertifi.net/services/")
        BigDecimal amount,
        @WebParam(name = "description", targetNamespace = "http://apps.sertifi.net/services/")
        String description,
        @WebParam(name = "recurrence", targetNamespace = "http://apps.sertifi.net/services/")
        PaymentReccurence recurrence,
        @WebParam(name = "datePaymentDue", targetNamespace = "http://apps.sertifi.net/services/")
        String datePaymentDue,
        @WebParam(name = "operation", targetNamespace = "http://apps.sertifi.net/services/")
        PaymentOperationType operation);

    /**
     * 
     * @param pFileID
     * @param pAPICode
     * @param paymentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemovePayment", action = "http://apps.sertifi.net/services/RemovePayment")
    @WebResult(name = "RemovePaymentResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemovePayment", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemovePayment")
    @ResponseWrapper(localName = "RemovePaymentResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemovePaymentResponse")
    public String removePayment(
        @WebParam(name = "p_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pAPICode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "paymentId", targetNamespace = "http://apps.sertifi.net/services/")
        String paymentId);

    /**
     * 
     * @param pFileID
     * @param pAPICode
     * @param paymentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPaymentsStatus", action = "http://apps.sertifi.net/services/GetPaymentsStatus")
    @WebResult(name = "GetPaymentsStatusResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "GetPaymentsStatus", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetPaymentsStatus")
    @ResponseWrapper(localName = "GetPaymentsStatusResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.GetPaymentsStatusResponse")
    public String getPaymentsStatus(
        @WebParam(name = "p_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pAPICode,
        @WebParam(name = "p_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pFileID,
        @WebParam(name = "paymentId", targetNamespace = "http://apps.sertifi.net/services/")
        String paymentId);

    /**
     * 
     * @param pstrFileID
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnableIDCheck", action = "http://apps.sertifi.net/services/EnableIDCheck")
    @WebResult(name = "EnableIDCheckResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "EnableIDCheck", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.EnableIDCheck")
    @ResponseWrapper(localName = "EnableIDCheckResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.EnableIDCheckResponse")
    public String enableIDCheck(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID);

    /**
     * 
     * @param pstrFormID
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddFormToRequest", action = "http://apps.sertifi.net/services/AddFormToRequest")
    @WebResult(name = "AddFormToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddFormToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddFormToRequest")
    @ResponseWrapper(localName = "AddFormToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddFormToRequestResponse")
    public String addFormToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_FormID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFormID,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle);

    /**
     * 
     * @param pstrFormID
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrAPICode
     * @param pstrXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddPrepopulatedFormToRequest", action = "http://apps.sertifi.net/services/AddPrepopulatedFormToRequest")
    @WebResult(name = "AddPrepopulatedFormToRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AddPrepopulatedFormToRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddPrepopulatedFormToRequest")
    @ResponseWrapper(localName = "AddPrepopulatedFormToRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AddPrepopulatedFormToRequestResponse")
    public String addPrepopulatedFormToRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_FormID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFormID,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "pstr_Xml", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrXml);

    /**
     * 
     * @param pstrUserEmail
     * @param pstrAPICode
     * @param pstrAutoFillUser
     * @param pstrUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AutofillUserName", action = "http://apps.sertifi.net/services/AutofillUserName")
    @WebResult(name = "AutofillUserNameResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "AutofillUserName", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AutofillUserName")
    @ResponseWrapper(localName = "AutofillUserNameResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.AutofillUserNameResponse")
    public String autofillUserName(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_UserEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrUserEmail,
        @WebParam(name = "pstr_UserName", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrUserName,
        @WebParam(name = "pstr_AutoFillUser", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAutoFillUser);

    /**
     * 
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrSignerEmail
     * @param pstrAPICode
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "CreateFaxShell", action = "http://apps.sertifi.net/services/CreateFaxShell")
    @WebResult(name = "CreateFaxShellResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "CreateFaxShell", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreateFaxShell")
    @ResponseWrapper(localName = "CreateFaxShellResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.CreateFaxShellResponse")
    public byte[] createFaxShell(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "pstr_SignerEmail", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrSignerEmail);

    /**
     * 
     * @param pblnMatchTitle
     * @param pstrFormID
     * @param pstrFileID
     * @param pstrTitle
     * @param pstrAPICode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveFormFromRequest", action = "http://apps.sertifi.net/services/RemoveFormFromRequest")
    @WebResult(name = "RemoveFormFromRequestResult", targetNamespace = "http://apps.sertifi.net/services/")
    @RequestWrapper(localName = "RemoveFormFromRequest", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveFormFromRequest")
    @ResponseWrapper(localName = "RemoveFormFromRequestResponse", targetNamespace = "http://apps.sertifi.net/services/", className = "net.sertifi.apps.services.RemoveFormFromRequestResponse")
    public String removeFormFromRequest(
        @WebParam(name = "pstr_APICode", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrAPICode,
        @WebParam(name = "pstr_FileID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFileID,
        @WebParam(name = "pstr_FormID", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrFormID,
        @WebParam(name = "pstr_Title", targetNamespace = "http://apps.sertifi.net/services/")
        String pstrTitle,
        @WebParam(name = "pbln_MatchTitle", targetNamespace = "http://apps.sertifi.net/services/")
        boolean pblnMatchTitle);

}
