#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 04-11-11 05:23 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.8.0.0
#endregion


namespace WebServices
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.sertifi.net/services/subscribers", TypeName="EventType")]
    public enum EventType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "FileCreated")]
        FileCreated,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "FileCompleted")]
        FileCompleted,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "FileReassigned")]
        FileReassigned,


        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "FileExpired")]
        FileExpired,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "StreamCommentAdded")]
        StreamCommentAdded,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AgreementCreated")]
        AgreementCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AgreementSigned")]
        AgreementSigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AgreementCompleted")]
        AgreementCompleted,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "AgreementExpired")]
        AgreementExpired,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "RequestReassigned")]
        RequestReassigned,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SignerDeclined")]
        SignerDeclined,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UserInvited")]
        UserInvited,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UserVisited")]
        UserVisited,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "PaymentFailed")]
        PaymentFailed,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "PaymentReceived")]
        PaymentReceived,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "PaymentRefunded")]
        PaymentRefunded,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name = "PaymentRemoved")]
        PaymentRemoved
    }
}
