#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 04-11-11 05:23 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.8.0.0
#endregion


namespace WebServices
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Web;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Web.Services.WebServiceAttribute(Namespace="http://apps.sertifi.net/services/subscribers")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EventPushSubscriberSoap", Namespace="http://apps.sertifi.net/services/subscribers", Location="EventPushSubscriber.wsdl")]
    public partial class EventPushSubscriber : System.Web.Services.WebService, IEventPushSubscriber
    {
        
        public EventPushSubscriber()
        {
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.sertifi.net/services/subscribers/ReceiveNotification", RequestNamespace="http://apps.sertifi.net/services/subscribers", ResponseNamespace="http://apps.sertifi.net/services/subscribers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Binding="EventPushSubscriberSoap")]
        public virtual void ReceiveNotification([System.Xml.Serialization.XmlElementAttribute(ElementName="notificationEvent")] NotificationEvent notificationEvent)
        {
            throw new System.NotImplementedException();
        }
    }
}
