#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 04-11-11 05:23 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.8.0.0
#endregion


namespace WebServices
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    public interface IEventPushSubscriber
    {
        
        void ReceiveNotification(NotificationEvent notificationEvent);
    }
}
