#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 04-11-11 05:23 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.8.0.0
#endregion


namespace WebServices
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.sertifi.net/services/subscribers", TypeName="NotificationEvent")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class NotificationEvent
    {
        
        /// <remarks/>
        private string securityToken;
        
        /// <remarks/>
        private string password;
        
        /// <remarks/>
        private EventType eventTypeId;
        
        /// <remarks/>
        private long eventId;
        
        /// <remarks/>
        private System.DateTime eventTime;
        
        /// <remarks/>
        private System.Collections.Generic.List<NotificationEventParameter> eventParameters;
        
        public NotificationEvent()
        {
        }
        
        public NotificationEvent(string securityToken, string password, EventType eventTypeId, long eventId, System.DateTime eventTime, System.Collections.Generic.List<NotificationEventParameter> eventParameters)
        {
            this.securityToken = securityToken;
            this.password = password;
            this.eventTypeId = eventTypeId;
            this.eventId = eventId;
            this.eventTime = eventTime;
            this.eventParameters = eventParameters;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SecurityToken")]
        public string SecurityToken
        {
            get
            {
                return this.securityToken;
            }
            set
            {
                if ((this.securityToken != value))
                {
                    this.securityToken = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Password")]
        public string Password
        {
            get
            {
                return this.password;
            }
            set
            {
                if ((this.password != value))
                {
                    this.password = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EventTypeId")]
        public EventType EventTypeId
        {
            get
            {
                return this.eventTypeId;
            }
            set
            {
                if ((this.eventTypeId != value))
                {
                    this.eventTypeId = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EventId")]
        public long EventId
        {
            get
            {
                return this.eventId;
            }
            set
            {
                if ((this.eventId != value))
                {
                    this.eventId = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EventTime")]
        public System.DateTime EventTime
        {
            get
            {
                return this.eventTime;
            }
            set
            {
                if ((this.eventTime != value))
                {
                    this.eventTime = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="EventParameters")]
        public System.Collections.Generic.List<NotificationEventParameter> EventParameters
        {
            get
            {
                return this.eventParameters;
            }
            set
            {
                if ((this.eventParameters != value))
                {
                    this.eventParameters = value;
                }
            }
        }
    }
}
